### ISSUE TITLE
When ask leader for usage, the usage is asked twice.

### ISSUE THREAD

**Issue by SafeteeWoW** [evil-morfar/RCLootCouncil2#113]
When the addon asks usage for leader, usage is asked once when I become the leader, and then another immediately after when it switches me to Master Looter. Don't know why this does not occur when testing in 2man group.

**Comment by evil-morfar** [comment]
It's because of ```addon.lootMethod```. Being leader marks you as ML. Entering a raid makes ```OnRaidEnter()``` show the popup, which runs ```StartHandleLoot()```, which in turn switches loot method, that gets picked up by ```NewMLCheck()```. Because of the the loot method check in line 1769 the function doesn't return even though the registered ML hasn't changed.

I see two ways of fixing this:

1. Delete the loot method check - I don't think it's actually needed to chek if that's changed? The only really relevant thing is the ML.
2. Do a check for ```self.handleLoot == false``` before doing usage actions.
