### ISSUE TITLE
Disable RC in pvp instance

### ISSUE THREAD

**Issue by SafeteeWoW** [evil-morfar/RCLootCouncil2#146]
Dont want to have RC popup and dont even want RC enabled in (premade) arena or battleground.
If I entered arena as raid group and when I am the first one who loaded into the arena, I keep getting RC popup, which is annoying.
should be very simple to fix

**Comment by evil-morfar** [comment]
I suppose that's a side effect of always having the group leader being registered as ML :)

Eitherway, `IsInInstance()` should fix that quite easily.

**Comment by SafeteeWoW** [comment]
I think add a line in GetML and NewMLCheck will do it, similar to ```if IsPartyLFG() then return end```
I think ```GROUP_LEFT``` will be fired when left pvp instance (not 100% sure), so things will perform normally after leaving pvp instance

**Comment by SafeteeWoW** [comment]
```if select(2, IsInInstance()) == "pvp" or select(2, IsInInstance()) == "arena" then return end```

**Comment by evil-morfar** [comment]
Yup, did that yesterday, just forgot to push it 5b388e18598a3ae2e4f686570e72f501bb075c00.

`PLAYER_ENTERING_WORLD` will at the very least be fired. One issue with this though, is it would create the popup whenever you leave pvp instead of entering, assuming one uses the "ask when leader" setting. I suppose doing the pvp check just before asking for usage will suffice. This way it'll keep any registered ML but just suppress any popups while pvping.
