### ISSUE TITLE
Wrong Items Being Assigned

### ISSUE THREAD

**Issue by jsmylnycky** [evil-morfar/RCLootCouncil2#191]
Hello!

Firstly, my guild has been using this addon all BFA long, and it's been pretty awesome, thank you :)

We have run into a problem every couple raids where it seems like some prior cached loot is overtaking assignments.  By this, I mean:

ItemA was previously assigned.
ItemB is up for roll.
ItemB is assigned to a player.
The output for the assignment is actually for ItemA, which wasn't even part of the encounter or available loot.
The window the player is given to trade the item to another gets confused with the wrong item.

I'll try to add more information as I get it, but is this something currently tracked anywhere?

Thanks!

**Comment by evil-morfar** [comment]
This happens if something is autoawarded between starting a session and finishing awarding items, or if something is autoawarded while the session frame is open.

I'm still trying to figure out why exactly it happens and what to do about it. I recommend finishing up sessions as soon as they started.

**Comment by jsmylnycky** [comment]
Glad to hear you're at least aware of the issue and the symptoms :) I'll pass along the information and hopefully now knowing what tends to cause the behavior, we can get into habits that bypass it.  Thanks! I'll keep an eye out for a resolution.
